In [1]:
import pandas as pd

In [2]:
mistral_advice_t1 = pd.read_csv('Results/AdviceGeneration/SampleResults/mistral_advice_t1.csv')
llama_advice_t1 = pd.read_csv('Results/AdviceGeneration/SampleResults/llama_advice_t1.csv')
gemma_advice_t1 = pd.read_csv('Results/AdviceGeneration/SampleResults/gemma_advice_t1.csv')
qwen_advice_t1 = pd.read_csv('Results/AdviceGeneration/SampleResults/qwen_advice_t1.csv')
phi_advice_t1 = pd.read_csv('Results/AdviceGeneration/SampleResults/phi_advice_t1.csv')

mistral_advice_t2 = pd.read_csv('Results/AdviceGeneration/SampleResults/mistral_advice_t2.csv')
llama_advice_t2 = pd.read_csv('Results/AdviceGeneration/SampleResults/llama_advice_t2.csv')
gemma_advice_t2 = pd.read_csv('Results/AdviceGeneration/SampleResults/gemma_advice_t2.csv')
qwen_advice_t2 = pd.read_csv('Results/AdviceGeneration/SampleResults/qwen_advice_t2.csv')
phi_advice_t2 = pd.read_csv('Results/AdviceGeneration/SampleResults/phi_advice_t2.csv')

In [7]:
# mistral_summary_t1 = pd.read_csv('Results/Summarization/SampleResults/mistral_summary_t1.csv')
# llama_summary_t1 = pd.read_csv('Results/Summarization/SampleResults/llama_summary_t1.csv')
# gemma_summary_t1 = pd.read_csv('Results/Summarization/SampleResults/gemma_summary_t1.csv')
# qwen_summary_t1 = pd.read_csv('Results/Summarization/SampleResults/qwen_summary_t1.csv')
# phi_summary_t1 = pd.read_csv('Results/Summarization/SampleResults/phi_summary_t1.csv')

# mistral_summary_t2 = pd.read_csv('Results/Summarization/SampleResults/mistral_summary_t2.csv')
# llama_summary_t2 = pd.read_csv('Results/Summarization/SampleResults/llama_summary_t2.csv')
# gemma_summary_t2 = pd.read_csv('Results/Summarization/SampleResults/gemma_summary_t2.csv')
# qwen_summary_t2 = pd.read_csv('Results/Summarization/SampleResults/qwen_summary_t2.csv')
# phi_summary_t2 = pd.read_csv('Results/Summarization/SampleResults/phi_summary_t2.csv')

In [3]:
for df in [mistral_advice_t1, llama_advice_t1, gemma_advice_t1, qwen_advice_t1, phi_advice_t1]:
    print("Original shape: ", df.shape, "Shape after dropping duplicates:", df.drop_duplicates().shape)
    print("Are all finish reasons stop, or are some length too?", set(df['finish_reason_t1'].values))
    print("Which narrative ids were processed?", set(df['narrative_idx'].values))
    print("Number of times narrative processed?", df[['narrative_idx', 'prompt_variant']].value_counts())
    
print()

for df in [mistral_advice_t2, llama_advice_t2, gemma_advice_t2, qwen_advice_t2, phi_advice_t2]:
    print("Original shape: ", df.shape, "Shape after dropping duplicates:", df.drop_duplicates().shape)
    print("Are all finish reasons stop, or are some length too?", set(df['finish_reason_t2'].values))
    print("Which narrative ids were processed?", set(df['narrative_idx'].values))
    print("Number of times narrative processed?", df[['narrative_idx', 'prompt_variant']].value_counts())

Original shape:  (6, 9) Shape after dropping duplicates: (6, 9)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2, 2055}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                1
               p2                1
               p3                1
2055           p1                1
               p2                1
               p3                1
Name: count, dtype: int64
Original shape:  (6, 9) Shape after dropping duplicates: (6, 9)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2, 2055}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                1
               p2                1
               p3                1
2055           p1                1
               p2                1
               p3                1
Name: count, dtype: int64
Original shape:  (6, 9) Shape after dropping duplicates: (6, 9)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2, 2055}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                1
               p2                1
               p3                1
2055           p1                1
               p2                1
               p3                1
Name: count, dtype: int64
Original shape:  (6, 9) Shape after dropping duplicates: (6, 9)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2, 2055}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                1
               p2                1
               p3                1
2055           p1                1
               p2                1
               p3                1
Name: count, dtype: int64
Original shape:  (6, 9) Shape after dropping duplicates: (6, 9)
Are all finish reasons stop, or are some length too? {'stop', 'length'}
Which narrative ids were processed? {2, 2055}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                1
               p2                1
               p3                1
2055           p1                1
               p2                1
               p3                1
Name: count, dtype: int64

Original shape:  (24, 12) Shape after dropping duplicates: (24, 12)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                8
               p2                8
               p3                8
Name: count, dtype: int64
Original shape:  (24, 12) Shape after dropping duplicates: (24, 12)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                8
               p2                8
               p3                8
Name: count, dtype: int64
Original shape:  (24, 12) Shape after dropping duplicates: (24, 12)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                8
               p2                8
               p3                8
Name: count, dtype: int64
Original shape:  (24, 12) Shape after dropping duplicates: (24, 12)
Are all finish reasons stop, or are some length too? {'stop'}
Which narrative ids were processed? {2}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                8
               p2                8
               p3                8
Name: count, dtype: int64
Original shape:  (24, 12) Shape after dropping duplicates: (24, 12)
Are all finish reasons stop, or are some length too? {'stop', 'length'}
Which narrative ids were processed? {2}
Number of times narrative processed? narrative_idx  prompt_variant
2              p1                8
               p2                8
               p3                8
Name: count, dtype: int64

(48, 12) (24, 12)
{'stop'}
(48, 12) (24, 12)
{'stop'}
(48, 12) (48, 12)
{'stop'}
(48, 12) (24, 12)
{'stop'}
(24, 12) (24, 12)
{'stop', 'length'}

In [17]:
for df in [mistral_summary_t1, llama_summary_t1, gemma_summary_t1, qwen_summary_t1]:
    print(df['n_tokens_t1'].describe())

count    14793.000000
mean       467.145407
std         87.975231
min        101.000000
25%        406.000000
50%        463.000000
75%        522.000000
max        959.000000
Name: n_tokens_t1, dtype: float64
count    14793.000000
mean       511.732711
std        130.406480
min          7.000000
25%        457.000000
50%        526.000000
75%        589.000000
max       1285.000000
Name: n_tokens_t1, dtype: float64
count    14793.000000
mean      1080.733590
std        124.127174
min        233.000000
25%       1010.000000
50%       1092.000000
75%       1164.000000
max       1643.000000
Name: n_tokens_t1, dtype: float64
count    14793.000000
mean       453.921449
std         78.611964
min        163.000000
25%        401.000000
50%        450.000000
75%        502.000000
max        879.000000
Name: n_tokens_t1, dtype: float64

In [8]:
llama_summary_t1.info()

,narrative_idx,narrative,nli_labels,prompt_variant,model,response_t1,n_tokens_t1,finish_reason_t1,batch_idx
0,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,llama,"Dear one,\n\nI'm so sorry to hear about the un...",615,stop,0
1,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,llama,"Dear one,\n\nYour story is a testament to the ...",455,stop,0
2,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p3,llama,"Dear friend,\n\nFirst and foremost, I want to ...",501,stop,0
3,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,llama,"Dear one,\n\nYour story is a testament to the ...",493,stop,0
4,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,llama,"Dear one,\n\nFirst and foremost, I want to ack...",506,stop,0

In [9]:
gemma_summary_t1.head()

,narrative_idx,narrative,nli_labels,prompt_variant,model,response_t1,n_tokens_t1,finish_reason_t1,batch_idx
0,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,gemma,"Okay, this is a profoundly difficult and heart...",1025,stop,0
1,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,gemma,"Okay, this is a profoundly difficult and heart...",1004,stop,0
2,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p3,gemma,"Okay, this is a profoundly difficult and harro...",1089,stop,0
3,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,gemma,"Okay, here’s a response addressing the person’...",926,stop,0
4,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,gemma,"Okay, here’s a response addressing the person’...",1048,stop,0

In [10]:
qwen_summary_t1.head()

,narrative_idx,narrative,nli_labels,prompt_variant,model,response_t1,n_tokens_t1,finish_reason_t1,batch_idx
0,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,qwen,"Dear you,\n\nFirst, allow yourself to fully pr...",480,stop,0
1,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,qwen,"Dear Professor Catherine Josephine Wilkins,\n\...",568,stop,0
2,0,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p3,qwen,"Dear [Your Name],\n\nFirst and foremost, I wan...",576,stop,0
3,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p1,qwen,"Dear Catherine,\n\nFirst and foremost, I under...",559,stop,0
4,1,Professor Catherine Josephine Wilkins mentally...,"{'clothing': 'contradiction', 'victim_intoxica...",p2,qwen,"Dear [Name],\n\nThank you for sharing your har...",536,stop,0