In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable

In [5]:
analysis = "DEMO"

In [37]:
narrative_normality = pd.read_csv(f'StatisticalTestResults/{analysis}/Narrative-NormalityCheck-noPOV.csv')
narrative_kruskalwallis = pd.read_csv(f'StatisticalTestResults/{analysis}/Narrative-KruskalWallis-noPOV.csv')
narrative_dunntest = pd.read_csv(f'StatisticalTestResults/{analysis}/Narrative-DunnTest-noPOV.csv')

In [38]:
narrative_normality['significant'].value_counts(dropna = False)

significant
True     22
False     8
Name: count, dtype: int64

In [39]:
narrative_kruskalwallis

,feature,kruskal_stat,p_value,eta2,significant,p_bh_corrected,alpha
0,childhood_abuse,129.354,8.150505e-29,0.0258,True,2.037626e-28,0.005
1,adult_victim,229.912,1.189135e-50,0.0462,True,1.189135e-49,0.005
2,victim_female,38.152,5.192001e-09,0.0073,True,5.768890e-09,0.005
3,victim_male,29.444,4.039678e-07,0.0056,True,4.039678e-07,0.005
4,perpetrator_female,134.989,4.869087e-30,0.0270,True,2.434543e-29,0.005
5,perpetrator_male,130.630,4.305173e-29,0.0261,True,1.435058e-28,0.005
6,stranger_assault,85.179,3.187927e-19,0.0169,True,6.375854e-19,0.005
7,acquaintance_assault,42.248,6.698664e-10,0.0082,True,8.373330e-10,0.005
8,family_member,78.494,9.020300e-18,0.0155,True,1.503383e-17,0.005
9,intimate_partner,45.421,1.371020e-10,0.0088,True,1.958600e-10,0.005

In [40]:
for i, row in narrative_kruskalwallis[['eta2']].iterrows():
    print(f"({i}, 1) [{row[0]}]")

for i, row in narrative_kruskalwallis[['significant']].iterrows():
    print(f"({i}, 0) [{row[0]}]")

(0, 1) [0.0258]
(1, 1) [0.0462]
(2, 1) [0.0073]
(3, 1) [0.0056]
(4, 1) [0.027]
(5, 1) [0.0261]
(6, 1) [0.0169]
(7, 1) [0.0082]
(8, 1) [0.0155]
(9, 1) [0.0088]
(0, 0) [True]
(1, 0) [True]
(2, 0) [True]
(3, 0) [True]
(4, 0) [True]
(5, 0) [True]
(6, 0) [True]
(7, 0) [True]
(8, 0) [True]
(9, 0) [True]

/tmp/ipykernel_2375374/3234313358.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"({i}, 1) [{row[0]}]")
/tmp/ipykernel_2375374/3234313358.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"({i}, 0) [{row[0]}]")

In [41]:
narrative_dunntest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   feature         30 non-null     object
 1   pair            30 non-null     object
 2   p_value         30 non-null     float64
 3   rank_biserial   30 non-null     float64
 4   significant     30 non-null     bool
 5   p_bh_corrected  30 non-null     float64
 6   alpha           30 non-null     float64
dtypes: bool(1), float64(4), object(2)
memory usage: 1.6+ KB

In [56]:
feature_order = ['childhood_abuse', 'adult_victim', 'victim_female', 'victim_male',
                 'perpetrator_female', 'perpetrator_male',
                 'stranger_assault', 'acquaintance_assault', 'family_member', 'intimate_partner']

pair_order = ['entailment vs neutral', 'entailment vs contradiction', 'neutral vs contradiction']

pivot = narrative_dunntest.pivot(index='feature', columns='pair', values='significant')
pivot = pivot.loc[feature_order, pair_order]

In [63]:
for i, row in pivot.iterrows():
    print(row[0], row[1], row[2])
    # print(f"(0, {i}) [{row[1]}] (1, {i}) [{row[2]}] (2, {i}) [{row[3]}]")

True True False
False True True
True True True
True True True
False True True
True True False
False True True
True True True
True True False
True True True

/tmp/ipykernel_2375374/1428954776.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(row[0], row[1], row[2])

In [50]:
narrative_dunntest

,feature,pair,p_value,rank_biserial,significant,p_bh_corrected,alpha
0,childhood_abuse,entailment vs neutral,2.523163e-29,-0.1601,True,3.784745e-28,0.001667
1,childhood_abuse,entailment vs contradiction,3.430300e-06,-0.0661,True,5.717167e-06,0.001667
2,childhood_abuse,neutral vs contradiction,8.817744e-01,-0.0021,False,8.817744e-01,0.001667
3,adult_victim,entailment vs neutral,5.163710e-01,-0.0092,False,5.532547e-01,0.001667
4,adult_victim,entailment vs contradiction,2.090188e-04,0.0528,True,3.135282e-04,0.001667
5,adult_victim,neutral vs contradiction,2.206058e-51,0.2147,True,6.618174e-50,0.001667
6,victim_female,entailment vs neutral,2.548101e-08,-0.0793,True,6.370252e-08,0.001667
7,victim_female,entailment vs contradiction,3.337059e-02,0.0303,True,4.352686e-02,0.001667
8,victim_female,neutral vs contradiction,2.830253e-07,0.0731,True,5.660505e-07,0.001667
9,victim_male,entailment vs neutral,6.801371e-08,-0.0768,True,1.457437e-07,0.001667
10,victim_male,entailment vs contradiction,3.210358e-06,-0.0663,True,5.665337e-06,0.001667
11,victim_male,neutral vs contradiction,3.850003e-02,0.0295,True,4.812503e-02,0.001667
12,perpetrator_female,entailment vs neutral,3.466847e-01,-0.0134,False,3.852053e-01,0.001667
13,perpetrator_female,entailment vs contradiction,6.290045e-10,0.0881,True,2.096682e-09,0.001667
14,perpetrator_female,neutral vs contradiction,9.696160e-26,0.1494,True,9.696160e-25,0.001667
15,perpetrator_male,entailment vs neutral,4.085998e-22,-0.1377,True,3.064499e-21,0.001667
16,perpetrator_male,entailment vs contradiction,1.490718e-13,-0.1052,True,6.388791e-13,0.001667
17,perpetrator_male,neutral vs contradiction,8.565113e-01,0.0026,False,8.817744e-01,0.001667
18,stranger_assault,entailment vs neutral,5.771640e-02,0.0270,False,6.925968e-02,0.001667
19,stranger_assault,entailment vs contradiction,1.013164e-03,0.0468,True,1.447377e-03,0.001667
20,stranger_assault,neutral vs contradiction,1.594662e-18,0.1251,True,7.973310e-18,0.001667
21,acquaintance_assault,entailment vs neutral,2.167049e-08,-0.0797,True,5.910134e-08,0.001667
22,acquaintance_assault,entailment vs contradiction,1.767316e-08,-0.0802,True,5.301949e-08,0.001667
23,acquaintance_assault,neutral vs contradiction,3.390307e-03,-0.0417,True,4.623146e-03,0.001667
24,family_member,entailment vs neutral,8.025252e-19,-0.1262,True,4.815151e-18,0.001667
25,family_member,entailment vs contradiction,3.088778e-08,-0.0788,True,7.127950e-08,0.001667
26,family_member,neutral vs contradiction,2.118962e-01,0.0178,False,2.444956e-01,0.001667
27,intimate_partner,entailment vs neutral,2.188985e-06,0.0674,True,4.104347e-06,0.001667
28,intimate_partner,entailment vs contradiction,2.024725e-11,0.0955,True,7.592719e-11,0.001667
29,intimate_partner,neutral vs contradiction,3.928111e-05,0.0586,True,6.202280e-05,0.001667