In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import seaborn as sns
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

In [4]:
kw = pd.read_csv('StatisticalTestResults/POST-MYTHS/KW-T2-delta.csv')
dunn = pd.read_csv('StatisticalTestResults/POST-MYTHS/Dunn-T2-delta.csv')

In [6]:
kw['significant'] = kw['p_value'] < 0.05

In [7]:
kw

          feature        stat       p_value  n_groups    eta2  significant
0           model   72.772647  1.087412e-15         4  0.1373         True
1            myth  176.824792  4.276924e-38         4  0.3422         True
2           frame   38.953702  1.775309e-08         4  0.0708         True
3            dose    2.041386  1.530701e-01         2  0.0020        False
4            task    6.354191  1.171043e-02         2  0.0105         True
5  prompt_variant    7.823001  2.001045e-02         3  0.0153         True

In [10]:
dunn

,feature,group1,group2,p_value,p_bh,significant,median_g1,median_g2,rank_biserial
0,model,gemma,llama,6.751932e-14,4.051159e-13,True,-0.6025,-0.3564,-0.4683
1,model,gemma,mistral,1.489610e-08,2.979220e-08,True,-0.6025,-0.3871,-0.3539
2,model,gemma,qwen,6.854068e-13,2.056220e-12,True,-0.6025,-0.3389,-0.4489
3,model,llama,mistral,6.727234e-02,1.009085e-01,False,-0.3564,-0.3871,0.1144
4,model,llama,qwen,7.563398e-01,7.563398e-01,False,-0.3564,-0.3389,-0.0194
5,model,mistral,qwen,1.286218e-01,1.543461e-01,False,-0.3871,-0.3389,-0.0950
6,myth,clothing,perpetrator_intoxication,5.276720e-16,1.055344e-15,True,-0.3509,-0.5875,0.5066
7,myth,clothing,resistance,4.746169e-13,7.119253e-13,True,-0.3509,-0.6142,0.4520
8,myth,clothing,victim_intoxication,3.115491e-03,3.738590e-03,True,-0.3509,-0.2361,-0.1848
9,myth,perpetrator_intoxication,resistance,3.828952e-01,3.828952e-01,False,-0.5875,-0.6142,0.0545
10,myth,perpetrator_intoxication,victim_intoxication,1.938003e-28,1.162802e-27,True,-0.5875,-0.2361,-0.6913
11,myth,resistance,victim_intoxication,2.232211e-24,6.696633e-24,True,-0.6142,-0.2361,-0.6368
12,frame,NegMyth,NegNonMyth,2.892055e-08,1.735233e-07,True,-0.5307,-0.3721,-0.3467
13,frame,NegMyth,PosMyth,4.330472e-03,8.660945e-03,True,-0.5307,-0.4164,-0.1783
14,frame,NegMyth,PosNonMyth,2.841991e-07,8.525974e-07,True,-0.5307,-0.3533,-0.3209
15,frame,NegNonMyth,PosMyth,7.042659e-03,1.056399e-02,True,-0.3721,-0.4164,0.1684
16,frame,NegNonMyth,PosNonMyth,6.787174e-01,6.787174e-01,False,-0.3721,-0.3533,-0.0259
17,frame,PosMyth,PosNonMyth,2.257175e-02,2.708610e-02,True,-0.4164,-0.3533,-0.1425
18,dose,1,2,1.530701e-01,1.530701e-01,False,-0.3933,-0.4379,0.0631
19,task,AdviceGeneration,Summarization,1.171043e-02,1.171043e-02,True,-0.4449,-0.3314,-0.1114
20,prompt_variant,p1,p2,1.837744e-02,2.756615e-02,True,-0.4783,-0.4111,-0.1474
21,prompt_variant,p1,p3,1.307194e-02,2.756615e-02,True,-0.4783,-0.4027,-0.1551
22,prompt_variant,p2,p3,9.014111e-01,9.014111e-01,False,-0.4111,-0.4027,-0.0077

In [14]:
for (i, row) in np.round(dunn[['rank_biserial']], 4).iterrows():
    print(f"(0, {i%6}) [{row[0]}] (1, {i%6}) [{row[0]}]")

(0, 0) [-0.4683] (1, 0) [-0.4683]
(0, 1) [-0.3539] (1, 1) [-0.3539]
(0, 2) [-0.4489] (1, 2) [-0.4489]
(0, 3) [0.1144] (1, 3) [0.1144]
(0, 4) [-0.0194] (1, 4) [-0.0194]
(0, 5) [-0.095] (1, 5) [-0.095]
(0, 0) [0.5066] (1, 0) [0.5066]
(0, 1) [0.452] (1, 1) [0.452]
(0, 2) [-0.1848] (1, 2) [-0.1848]
(0, 3) [0.0545] (1, 3) [0.0545]
(0, 4) [-0.6913] (1, 4) [-0.6913]
(0, 5) [-0.6368] (1, 5) [-0.6368]
(0, 0) [-0.3467] (1, 0) [-0.3467]
(0, 1) [-0.1783] (1, 1) [-0.1783]
(0, 2) [-0.3209] (1, 2) [-0.3209]
(0, 3) [0.1684] (1, 3) [0.1684]
(0, 4) [-0.0259] (1, 4) [-0.0259]
(0, 5) [-0.1425] (1, 5) [-0.1425]
(0, 0) [0.0631] (1, 0) [0.0631]
(0, 1) [-0.1114] (1, 1) [-0.1114]
(0, 2) [-0.1474] (1, 2) [-0.1474]
(0, 3) [-0.1551] (1, 3) [-0.1551]
(0, 4) [-0.0077] (1, 4) [-0.0077]

/tmp/ipykernel_2322655/3047324408.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"(0, {i%6}) [{row[0]}] (1, {i%6}) [{row[0]}]")

In [16]:
for (i, row) in np.round(dunn[['significant']], 4).iterrows():
    print(f"(0, {i%6}) [{row[0]}] (1, {i%6}) [{row[0]}]")

(0, 0) [True] (1, 0) [True]
(0, 1) [True] (1, 1) [True]
(0, 2) [True] (1, 2) [True]
(0, 3) [False] (1, 3) [False]
(0, 4) [False] (1, 4) [False]
(0, 5) [False] (1, 5) [False]
(0, 0) [True] (1, 0) [True]
(0, 1) [True] (1, 1) [True]
(0, 2) [True] (1, 2) [True]
(0, 3) [False] (1, 3) [False]
(0, 4) [True] (1, 4) [True]
(0, 5) [True] (1, 5) [True]
(0, 0) [True] (1, 0) [True]
(0, 1) [True] (1, 1) [True]
(0, 2) [True] (1, 2) [True]
(0, 3) [True] (1, 3) [True]
(0, 4) [False] (1, 4) [False]
(0, 5) [True] (1, 5) [True]
(0, 0) [False] (1, 0) [False]
(0, 1) [True] (1, 1) [True]
(0, 2) [True] (1, 2) [True]
(0, 3) [True] (1, 3) [True]
(0, 4) [False] (1, 4) [False]

/tmp/ipykernel_2322655/1445174520.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"(0, {i%6}) [{row[0]}] (1, {i%6}) [{row[0]}]")